DmlDemo.dmlDemoMultipleUpdate_right2();
DmlDemo.dmlDemoMultipleUpdate_right1();
DmlDemo.dmlDemoMultipleInsert_right2();
DmlDemo.dmlDemoMultipleInsert_right1();
DmlDemo.dmlDemoInsert_cstmObj2();
DmlDemo.dmlDemoInsert_stndObj1();
DmlDemo.dmlDemoInsert_cstmObj();
DmlDemo.dmlUpdateDemo_stndObj1();
DmlDemo.dmlUpdateDemo_stndObj2();
DmlDemo.dmlInsertDemo_stndObj2();
DmlDemo.dmlDemoInsert_wrong1();


delete [select id from account where createddate = TODAY limit 70];