string firstVariable = 'this is our first string variable';
System.debug(firstVariable);

string firstName = 'Vitap';
string lastName = 'Ramdevputra';
string fullName = firstName + ' ' + lastName;
system.debug('full name is ... ' + fullName);

//Deploy class.
//Execute anonymous apex

string declareString; //declaring a variable
system.debug(declareString);

string defineString = 'this is a string';